### ISSUE TITLE
[docs] 레포지토리에 컨트리뷰트하기 용이한 적절한 이슈 템플릿을 만든다.

### ISSUE THREAD

**Issue by JengYoung** [FE-DeepDive/JavaScript-DeepDive#1]
# 📋 설명

현재 우리 레포지토리에는 이슈를 등록할 만한 특정 템플릿이 없어서, 이후에 이슈를 등록할 때 중구난방이 될 것 같아요!
이런 이유 때문에 뭔가 아직은 적극적으로 올리기도 망설여지는 것 같기도 하구요.

오늘 피드백 때, 함께 이를 논의해보면 좋을 것 같아요 👏🏻
저도 예시를 한 번 준비해보겠습니다!

# ✨ 목표

- [x] 모두가 편하게 이슈를 등록할 수 있는 이슈 템플릿(PR 템플릿도 있으면 좋을 것 같습니다)을 생성한다.
- [x] 현재 레포지토리에서의 <이슈> 용도를 정확히 정의하여, 이에 대한 카테고리를 세분화하여 템플릿을 구성한다.

## 생성 과정

이슈 템플릿 생성 방법은 크게 2가지가 있어요.
1. 마크다운 형식으로 디렉토리를 직접 생성하는 방식
2. UI를 통해 템플릿 생성하는 방식

우리는 2번째로 하는 게 더 편할 것 같은데, 아무래도 현재 저희가 권한이 없어서 정희님께서 만들어주셔야 할 거에요!

> 나름대로 생성 방법에 대해서 서술하고자 하는데, 이는 다른 팀원들도 나중에 자신의 레포지토리를 잘 꾸려나가기 위한 팁입니다! 🚀

### 1. 먼저 `Settings`로 들어가세요! 
<img width="831" alt="image" src="https://user-images.githubusercontent.com/78713176/186436131-3cdd8944-a6dd-4c45-9f94-22d9ee03676f.png">

### 2. Custom Template을 클릭하세요! (저 툴팁은 제 익스텐션입니다 😅)
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/78713176/186439745-926b2171-06e1-4189-8bec-2814acc16402.png">

### 3. 연필 아이콘을 눌러 수정해주시면 됩니다!
<img width="801" alt="image" src="https://user-images.githubusercontent.com/78713176/186439852-8398f552-c11b-4aba-b0ba-8aec6a02d41b.png">
<img width="771" alt="image" src="https://user-images.githubusercontent.com/78713176/186440483-29c41ea8-4811-4aa6-940e-5fc8cbda3217.png">

### 4. 우측 상단의 `proposal changes`를 누릅니다!
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/78713176/186444915-912cc20f-2503-424a-b301-9ccda01f554e.png">

### 5. 하단의 라디오 버튼에 체크해주세요!

> 😮 왜 하단의 라디오 버튼을 체크하나요?
> 📢 웬만하면 다같이 협업하는 레포지토리는 3-ways-merge를 권장하는 편입니다. 만약 다이렉트로 커밋에 푸시를 하면, 나중에 혹여나 저것이 업데이트를 하는 경우 등이 있을 때, 저 커밋을 봐야만 히스토리를 이해할 수 있어서 서로 공유하기가 힘들어져요. 😅 따라서 PR 후 충분한 메시지를적어서 머지하기를 권장합니다.

<img width="453" alt="image" src="https://user-images.githubusercontent.com/78713176/186445953-cf34cc3a-c3ba-4b61-9b2f-22b3e40e5b35.png">

### 6. 브랜치 생성과 동시에 커밋 푸시 후 자동으로 PR이 나오면 머지.

메시지를 이미 적어놓았으면 괜찮게 설명이 되어져 있을 거에요. 서로 협의가 되었다면 바로 머지하죠!

<img width="936" alt="image" src="https://user-images.githubusercontent.com/78713176/186446266-74b9d01e-71b3-4375-af67-652a17dc78de.png">

**Comment by chilldata** [comment]
좋은 의견입니다! 오늘 같이 회의 때 논의해보아요.

**Comment by JengYoung** [comment]
아무래도 우리가 스터디이고, 마크다운 위주의 아카이브를 구축할 것 같아서 저는 다음과 같은 템플릿 분류를 건의할게요!

# 1. [문서 추가] 문서를 추가합니다!

## 🚦 배경

> 문서를 추가하게 된 배경이 있으신가요? 간단히 설명해주세요!

## ✅ 체크리스트

> 해당 문서에는 어떤 내용들이 들어가 있어야 할까요? 사전에 체크하면서 문서를 완성해봅시다!

## 📑 참고자료

> 사전에 모두가 이 이슈를 이해하는 데 필요한 참고 자료를 공유해주세요! 🙆🏻

---

# 2. [문서 수정] 문서를 수정합니다!

## 🚦 배경

> 문서를 수정하게 된 배경이 있으신가요? 간단히 설명해주세요!

- [ ] 글자나 맞춤법이 틀렸어요! ✏️
- [ ] 내용이 잘못된 것 같아요! 확인해주세요! 🙇🏻‍♂️
- [ ] 기타 `해당 빈칸을 채워주세요!`

### 참고자료

> 만약 내용이 잘못된 것이라면, 이에 관련한 참고자료를 꼭 적어주세요! 
> 모두가 함께 관리하는 문서이므로, **정보에 대한 신뢰성**이 꼭 필요하기 때문입니다 🥲

## 📢 제안하는 내용

### before

```markdown
# 이전의 내용은 이랬는데요!
```

### after

```markdown
# 이렇게 제안합니다!
```

**Comment by JengYoung** [comment]
마크다운 코드는 다음과 같아요! (**\```markdown**의 경우는 역슬래시 제거)

# 1. [문서 추가] 문서를 추가합니다!
```
## 🚦 배경

> 문서를 추가하게 된 배경이 있으신가요? 간단히 설명해주세요!

## ✅ 체크리스트

> 해당 문서에는 어떤 내용들이 들어가 있어야 할까요? 사전에 체크하면서 문서를 완성해봅시다!

## 📑 참고자료

> 사전에 모두가 이 이슈를 이해하는 데 필요한 참고 자료를 공유해주세요! 🙆🏻
```
---

# 2. [문서 수정] 문서를 수정합니다!

```
## 🚦 배경

> 문서를 수정하게 된 배경이 있으신가요? 간단히 설명해주세요!

- [ ] 글자나 맞춤법이 틀렸어요! ✏️
- [ ] 내용이 잘못된 것 같아요! 확인해주세요! 🙇🏻‍♂️
- [ ] 기타 `해당 빈칸을 채워주세요!`

### 참고자료

> 만약 내용이 잘못된 것이라면, 이에 관련한 참고자료를 꼭 적어주세요! 
> 모두가 함께 관리하는 문서이므로, **정보에 대한 신뢰성**이 꼭 필요하기 때문입니다 🥲

## 📢 제안하는 내용

### before

\```markdown
# 이전의 내용은 이랬는데요!
\```

### after

\```markdown
# 이렇게 제안합니다!
\```
```

**Comment by chilldata** [comment]
자세하게 작성해주셨네요! 이번주 일요일까지 적용해놓겠습니다 :)

**Comment by JengYoung** [comment]
#2 에서 머지가 완료되었으므로 해당 이슈를 종료합니다 😉
